#!/bin/bash

set -o errexit

git remote rm                   origin
git remote add                  origin git@github.com:subhelion/forge.subhelion.com.git
git remote set-url --add --push origin git@github.com:subhelion/forge.subhelion.com.git
git remote set-url --add --push origin git@github.com:belimoth/forge.subhelion.com.git
